---
- name: update web server
  hosts: web
 
  tasks:
  - name: ensure web directory
    file:
    
     path: /home/centos/web-directory
     state: directory
  tasks:
  - name: endure file download
    get_url:

     url: https://filesamples.com/samples/document/txt/sample2.txt
     dest: /home/centos/

